### PR TITLE
fix: display hex message on bulletin board

### LINKED ISSUE #285: Adicionar suporte HEX no BB
**Describe the bug**
Ao usar HEX no quadro de avisos as cores são traduzidas para legacy.

**To Reproduce**
1. Use o comando para alterar a tag de um clã.
2. Use o comando para visualizar a mensagem no quadro de avisos.
3. Veja a cor da tag na mensagem.

**Expected behavior**
A cor da TAG ser em HEX

**Screenshots**
image

**Software (please complete the following information):**
 - Server: 1.17.1
 - Plugin version: 1.16.2

### PR DESCRIPTION
**Pull request by SrBedrock**
fix #285 and added escape in bb.days
I tested version 1.8 and the default color codes (&a, &b...) are working correctly

image

### CODE REVIEW

**Review by Tomut0 — CHANGES_REQUESTED** [review]
изображение
Doesn't work for me. 👀

**Comment by SrBedrock** [comment]
image

After so many attempts I ended up getting confused with PR, solved.

File: src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java [hunk 1]
```diff
@@ -1358,12 +1358,12 @@ private boolean sendBbTime(Player player, String msg) {
             long time = (System.currentTimeMillis() - Long.parseLong(msg.substring(0, index))) / 1000L;
             msg = ChatUtils.parseColors(bbPrefix + msg.substring(++index));
 
-            TextComponent textComponent = new TextComponent(msg);
+            TextComponent textComponent = new TextComponent(TextComponent.fromLegacyText(msg));
             textComponent.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, TextComponent.fromLegacyText(
                     Dates.formatTime(time, 1) + lang("bb.ago"))));
             player.spigot().sendMessage(textComponent);
```
Comment (Tomut0) [inline src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java]: I think we can use BaseComponent[] here.

[player.spigot().sendMessage(net.md_5.bungee.api.chat.BaseComponent...)](
https://helpch.at/docs/1.15.2/org/bukkit/entity/Player.Spigot.html#sendMessage-net.md_5.bungee.api.chat.BaseComponent...)

**Review by Tomut0 — APPROVED** [review]
