### PR TITLE
fix: NPE while sending a message to spies

### LINKED ISSUE #321: [Bug] [ACF] NPE Cannot invoke "net.sacredlabyrinth.phaed.simpleclans.ClanPlayer.toPlayer()" because "cp" is null
**Describe the bug**
Erro no console:

```
[15:10:43 INFO]: PabloGamingg issued server command: /c caraca vei
[15:10:43 ERROR]: [SimpleClans] [ACF] Exception in command: c caraca vei
[15:10:43 ERROR]: [SimpleClans] [ACF] java.lang.NullPointerException: Cannot invoke "net.sacredlabyrinth.phaed.simpleclans.ClanPlayer.toPlayer()" because "cp" is null
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.chat.handlers.SpyChatHandler.lambda$getOnlineClanPlayers$3(SpyChatHandler.java:51)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.chat.handlers.SpyChatHandler.getOnlineClanPlayers(SpyChatHandler.java:52)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.chat.handlers.SpyChatHandler.sendMessage(SpyChatHandler.java:34)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.managers.ChatManager.processChat(ChatManager.java:97)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.commands.clan.ChatCommand.sendMessage(ChatCommand.java:30)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at jdk.internal.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BaseCommand.execute(BaseCommand.java:513)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.acf.RootCommand.execute(RootCommand.java:99)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at SimpleClans-2.17.0.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2308)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2119)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2100)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1505)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1227)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317)
[15:10:43 ERROR]: [SimpleClans] [ACF]   at java.base/java.lang.Thread.run(Thread.java:833)
[15:10:43 INFO]: [SimpleClans] [c] [TOP] [s Membro s] PabloGamingg» caraca vei
```

**To Reproduce**
Não sei como reproduzir, apenas encontrei no console.

**Expected behavior**
Nenhum erro no console.

**Software (please complete the following information):**
 - Server: 1.18.2
 - Plugin version: 2.16.2-51f82ba

**Additional context**

### PR DESCRIPTION
**Pull request by Tomut0**
Solves #321

### CODE REVIEW

**Comment by RoinujNosde** [comment]
Strange that a ClanPlayer returned by getAllClanPlayers() was null.

**Comment by Tomut0** [comment]
> Strange that a ClanPlayer returned by getAllClanPlayers() was null.

I noticed that too.
I don't think that chat implementation needs to handle `null` of getAllClanPlayers().
If you will look over the PR I made that check **implicitly**.
It's better than retrieving NPE, IMO.

**Comment by Tomut0** [comment]
It's like your love to set `@Nullable` of parameter and then `return` in a method.

**Comment by RoinujNosde** [comment]
> I don't think that chat implementation needs to handle null of getAllClanPlayers().

It shouldn't even have a null element. The bug is hidden somewhere else.

File: src/main/java/net/sacredlabyrinth/phaed/simpleclans/chat/handlers/SpyChatHandler.java [hunk 1]
```diff
@@ -13,42 +14,37 @@
...
-        return source == SPIGOT || (source == DISCORD && settingsManager.is(DISCORDCHAT_ENABLE) &&
-                getPluginManager().getPlugin("DiscordSRV") != null);
+        return source == SPIGOT || (source == DISCORD && chatManager.isDiscordHookEnabled());
     }
 
-    private List<ClanPlayer> getOnlineClanPlayers() {
-        return plugin.getClanManager().getAllClanPlayers().stream().
-                filter(cp -> cp.toPlayer() != null).
+    private List<ClanPlayer> getOnlineSpies() {
+        return Bukkit.getOnlinePlayers().stream().
```
Comment (RoinujNosde) [inline src/main/java/net/sacredlabyrinth/phaed/simpleclans/chat/handlers/SpyChatHandler.java:45]: add a filter for Objects::requireNonNull, just in case
as Stream is suspected to be the cause 🤡

**Review by RoinujNosde — CHANGES_REQUESTED** [review]

**Review by RoinujNosde — APPROVED** [review]
